version: '3.8'

services:
  server:
    image: youthing/manito-cotato:1.0.2
    container_name: manito-cotato
    ports:
      - "5000:8080"
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: